DATAS SEGMENT
    BUF DB 10 DUP($)			;开辟10个字节的空间
DATAS ENDS

STACKS SEGMENT
    ;此处输入堆栈段代码
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
START:
    MOV AX,DATAS
    MOV DS,AX
    LEA DX,BUF ;设置DX,使字符串首地址=DS:DX
    MOV AH,0A
    INT 21H
    MOV AH,4CH
    INT 21H
CODES ENDS
    END START
;一个寄存器有两个字节
